adding jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -2,15 +2,24 @@ pipeline {
     agent any
     environment {
         DOCKERHUB_CREDENTIALS = credentials('dockerhubpat')
-        IMAGE_NAME = 'raparna154/sample'
+        IMAGE_NAME = 'raparna154/inji-verify-service:latest'
+        GIT_BRANCH = 'test' 
     }
     stages {
 
+        stage('Clean Workspace') {
+            steps {
+                sh 'rm -rf e2e_inji_verify || true'
+            }
+        }
+
         stage('Checkout') {
             steps {
-                git branch: 'main',
+                    git branch: 'main',
                     url: 'https://github.com/pkumarmshetty/e2e_inji_verify.git',
                     credentialsId: 'githubpat2'
+                    cd e2e_inji_verify
+                    git checkout $GIT_BRANCH
             }
         }
 
@@ -20,16 +29,20 @@ pipeline {
                 //git url: 'https://github.com/pkumarmshetty/e2e_inji_verify.git', branch: 'test'
             //}
         //}
-         stage('Build with Maven') {
-            steps {
+         //stage('Build with Maven') {
+           // steps {
                 // Run Maven build using shell command
-                sh 'mvn -U -B clean package'
-            }
-        }
+                //sh 'mvn -U -B clean package'
+            //}
+        //}
         stage('Build Docker Image') {
             steps {
                 script {
-                    dockerImage = docker.build("${IMAGE_NAME}:${BUILD_NUMBER}", "-f verify-service/Dockerfile .")
+                    dir('e2e_inji_verify/ui') {
+                        sh """
+                        docker build -t $DOCKER_IMAGE .
+                        """
+                    }
                 }
             }
         }
@@ -42,18 +55,13 @@ pipeline {
                 }
             }
         }
-        //stage('Run Docker Container') {
-            //steps {
-                //sh """
-                //docker run -d -p 3000:8000 --env-file ./.env --name inji-verify-service-dev ${IMAGE_NAME}:${BUILD_NUMBER}
-                //"""
-            //}
-        //}
     }
     post {
-        cleanup {
-            sh 'docker rmi ${IMAGE_NAME}:${BUILD_NUMBER}'
+        success {
+            echo 'Pipeline completed successfully!'
+        }
+        failure {
+            echo 'Pipeline failed!'
         }
     }
 }
-
